### ISSUE TITLE
BenchmarkWrapped fails with an NPE

### ISSUE THREAD

**Issue by PaintNinja** [MinecraftForge/EventBus#59]
When running `gradlew jmh`, it fails near the end due to an NPE in BenchmarkWrapped:
```
java.lang.NullPointerException: Cannot invoke "java.lang.Runnable.run()" because "this.run" is null
	at net.minecraftforge.eventbus.jmh/net.minecraftforge.eventbus.benchmarks.BenchmarkBase.run(BenchmarkBase.java:130)
	at net.minecraftforge.eventbus.jmh/net.minecraftforge.eventbus.benchmarks.BenchmarkWrapped.postDynamic(BenchmarkWrapped.java:19)
	at net.minecraftforge.eventbus.jmh/net.minecraftforge.eventbus.benchmarks.jmh_generated.BenchmarkWrapped_postDynamic_jmhTest.postDynamic_avgt_jmhStub(BenchmarkWrapped_postDynamic_jmhTest.java:310)
	at net.minecraftforge.eventbus.jmh/net.minecraftforge.eventbus.benchmarks.jmh_generated.BenchmarkWrapped_postDynamic_jmhTest.postDynamic_AverageTime(BenchmarkWrapped_postDynamic_jmhTest.java:232)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at jmh.core@1.37-module/org.openjdk.jmh.runner.BenchmarkHandler$BenchmarkTask.call(BenchmarkHandler.java:527)
	at jmh.core@1.37-module/org.openjdk.jmh.runner.BenchmarkHandler$BenchmarkTask.call(BenchmarkHandler.java:504)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:840)
```

**Comment by LexManos** [comment]
Turns out I git ignored the wrapper project, and had a typo (an extra semicolon) that made it not optional. My bad.
The wrapper is a wrapper around neo's fork so that it can be benched in the exact same way as the rest of things.
I didn't commit it because I didn't want to deal with the drama/headake. So it's kept local for now. 
Paint has a copy if he feels like testing it. But honestly anything that touches that stuff is just asking for drama and I don't want to deal with it.

Anyways fixed the derp NPE by 1) fixing the typo and 2) removing the Wrapped benchmark from the repo.
https://github.com/MinecraftForge/EventBus/compare/6fb1fcc90c65...f29ef3d81dee
